### ISSUE TITLE
Syntax error in that onClick handler.

### ISSUE THREAD

**Issue by mircealungu** [beamb/microlearning#11]
Actually, the build script is right: you do have a syntax error in that onClick handler. 
The correct code has one extra pair of `{}`, i.e.:

```
      onClick={() => {
        console.log(props.number + " questions has been clicked.");
        // sets the interruption in state to n questions
        setInterruption(props.number);
      }}
```

_Originally posted by @mircealungu in https://github.com/beamb/microlearning/pull/8#issuecomment-725375473_

**Comment by sdsmoni** [comment]
The error was fixed
