### ISSUE TITLE
i'm not sure I get the data model :)

### ISSUE THREAD

**Issue by mircealungu** [beamb/microlearning#13]
the single paragraph of text makes it hard to understand what you plan to do :)

intuitively it seems to me that your answers "containing text and an indication of false or true values for each question" are not saving the info about which user has provided an answer. or? and then the question is... does it make more sense to have the answers in the questions, or the answers embedded in a user instead? because you'll have multiple users answer the same question.

finally, an answer should have also a timestamp maybe? otherwise how are you going to model the fact that yesterday i was wrong, but today i'm right?

From a reviewer's POV, I found this kind of data modeling specification format to be easier to read: https://github.itu.dk/gbro/TID-Group-1#data-model

**Comment by sdsmoni** [comment]
I merged the drawing update for the model; it should be in Main now. I'll take a look at the link, but yes, we might need to rethink our data model because if we need to fetch all the data to store in a local array, what is the point of a database storing in the first place?

**Comment by mircealungu** [comment]
hmm. good question! 
if you want the data to follow the user than it makes sense.
(e.g. say i have two machines and i install the extension on both.)

but for a prototype, this might not be necessary indeed and you could get away with localHost I think.
@madsnedergaard  do you agree?

**Comment by sdsmoni** [comment]
we decided to go with the localHost for the prototype and since we have the users' collections up and running we will try to implement adding the questions to the users' collections base on the language choice.
