### ISSUE TITLE
Help with React Hook - TID course

### ISSUE THREAD

**Issue by madsnedergaard** [beamb/microlearning#43]
Hey team (@beamb), got your mail - let's talk about it here so everyone can follow-along and I can get better formatting than in emails :) 

> In our microlearning extension we’d like to throw confetti when a user picks the correct answer. The red/green colour coding makes sense to users who pick the wrong answer every now and then but users who get it all right every time said they were confused and unsure whether or not their answers were correct.
>
> I was able to get the confetti to run only once. It seems like I should somehow let react know that the Confetti Hook should be re-mounted on every render :-/ Is there a way of doing that?
>
> This is the Hook I’m using to run the confetti (and it has a run={true/false} attribute): https://www.npmjs.com/package/react-confetti

## Debugging the problem

Alrighty, let's first figure out what's going on:

1. The component is always rendered, 
2. when user has answered correctly, we set `isCorrect` to true,
3. and that sets `run={true}` on the component.
4. This will stop the animation, but this will just stop/pause the animation and not make it run from the top again.

I tried to set isCorrect=false when user clicks on the "next" button. See example here:

![Kapture 2020-11-29 at 21 14 48](https://user-images.githubusercontent.com/3296643/100552527-07a30f80-3288-11eb-94ff-65e5df885c68.gif)

### Conclusion

It seems to me that the issue is that there is no built-in way to reset or rerun the animation in that component. We can only start/pause the animation, but that doesn't help us much. Therefore we need to ensure the component is only rendered when it should show. 

## Solution

A solution to this could be to only render component if `isCorrect` is `true`. That requires that you set `isCorrect` to `false`, which you can do in two ways (depending on what UX you prefer):

### Solution 1: Stop confetti when user clicks "next"

This will remove the confetti if it's still falling.

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/3296643/100552692-f9a1be80-3288-11eb-8d1a-a194da7946cc.png">

![Kapture 2020-11-29 at 21 25 27](https://user-images.githubusercontent.com/3296643/100552926-b9dbd680-328a-11eb-9204-14aef5c9a5d1.gif)

### Solution 2: Stop confetti when it's done

This will let the confetti continue after user clicks next, and if user is answering the next question too quickly, the confetti will not show (because it's not done from the last question)

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/3296643/100552901-8dc05580-328a-11eb-846e-f1b5ca211ac1.png">

![Kapture 2020-11-29 at 21 36 17](https://user-images.githubusercontent.com/3296643/100552959-045d5300-328b-11eb-966a-0ecb039a42d5.gif)

---

Phew, all done! Hope that makes sense and helps you :)

PS. The gifs here are lagging because I set a low framerate to make them smaller, it runs fine om my computer!

**Comment by beamb** [comment]
Thank you @madsnedergaard ! Argh I was so close!! I had a version with setting `isCorrect` to false when clicking "Next" but had the same issue as you in the beginning so I gave up that route. I always forget it's possible to render conditionally with the `isCorrect && <.../>`. Thank you so much :-) 

PS. I hope you like the confetti :-D

**Comment by madsnedergaard** [comment]
> Thank you @madsnedergaard ! Argh I was so close!! I had a version with setting `isCorrect` to false when clicking "Next" but had the same issue as you in the beginning so I gave up that route. I always forget it's possible to render conditionally with the `isCorrect && <.../>`. Thank you so much :-)
> 
> PS. I hope you like the confetti :-D

Haha, happy that you were close - it's such an annoying feeling when you're actually on the right path, but just missed the last step 😄 

And yes, it's very nice! 🎉
