### ISSUE TITLE
Cannot make sense of chrome.browserAction.openPopup(callback: function)

### ISSUE THREAD

**Issue by beamb** [beamb/microlearning#54]
In f8112e010fd8e1daaac47da7a68e165d4709f82f I tried to programmatically open the popup when visiting "developer.chrome.com". However, I'm struggling to understand how to write the callback function.

[Here](https://developer.chrome.com/docs/extensions/reference/browserAction/#method-openPopup) it says that "The callback parameter should be a function that looks like this:"
`(popupView: object) => {...}`
And popupView is described as "JavaScript 'window' object for the popup window if it was succesfully opened.".

I've tried `() => {window.open("index.html");}`, `(popupView: Window) => {popupView.open("index.html");}`, `(popupView: window) => {popupView.open("index.html");}`, `(popupView: object) => {popupView.window.open("index.html");}`, `function(popupView) {popupView.open("index.html");}` and many more variations of these. The main issue is that I simply cannot understand how this function should be structured. Is popupView an object or any object? Do I need to define the type of object? Is popupView only a 'window' object if the popup opened successfully? If so, what callback function is needed? I'm super confused 😓

Thanks for any tips 🙏🏽

**Comment by mircealungu** [comment]
@beamb 

A first confusion that i see is the notation: `popupView: object`. If you look at other examples in that page, you'll see that the syntax of the function arguments is: `<exampleVarName>: <varType>`. E.g. look at the following function definition: 

    setBadgeText(details: object, callback: function)

this tells you that the `setBadgeText` expects two args: `details` and `callback` and that the first is an object, and that the second is a function. surely, `details` is just an example; you could name it something else if you wanted. 

Thus, the way you call the `openPopup` is:

    openPopup(callback: function)

This means, that `openPopup` expects a callback function. About this function, you learn below that it will receive when called as argument the object representing the newly opened window. 

thus you need something like this: 

    openPopup( newWindow => {
        console.log("now you have access to the newWindow object that's your popup window");
        console.log(newWindow);  
    });

Obviously, in your example you're trying to open 'index.html' , but as far as I can see, openPopup does not take a file name as argument. Instead, it "Opens the extension popup window"... (Here, not having much experience with extensions, I imagine that you might be able to set the `newWindow.location` variable and maybe you'll in this way load the page you want after the popup has been loaded?)

I hope this helps!

**Comment by beamb** [comment]
@mircealungu 

Thank you so much!! This already helps a lot! There were a bit too many layers for me to unpack but your break down helped me make sense of it all. Thank you again!
