### ISSUE TITLE
Dead link in report

### ISSUE THREAD

**Issue by madsnedergaard** [beamb/microlearning#62]
Hey team, the link in your report on page 11 ("The improved high-fidelity prototype based on the usability testing report can be accessed **here**.") isn't working. 
Did you make it publicly available?

Hope it's just the viewing permissions, as it's a bit too late to do change it in the report 😅 

https://www.figma.com/proto/vqZB1x4MtyDP1CvVCDXBB2/Interruption-prompt-High-fidelity-V2?scaling=contain&node-id=9

<img width="775" alt="image" src="https://user-images.githubusercontent.com/3296643/103575975-bdd6c600-4ed2-11eb-860d-2e2fb1d9d77b.png">

@beamb @sdsmoni @anneschjoedt @clka

**Comment by anneschjoedt** [comment]
Hey Mads. I changed the permissions. Hope it works now!

**Comment by madsnedergaard** [comment]
It does indeed, thanks for the swift response!
